### ISSUE TITLE
修改配置问题

### ISSUE THREAD

**Issue by ITBOX-ITBOY** [weizhixiaoyi/DouBan-KGQA#1]
@prefix tdb:     <http://jena.hpl.hp.com/2008/tdb#> .
@prefix ja:      <http://jena.hpl.hp.com/2005/11/Assembler#> .
这两个要怎么样修改呀，没有太弄明白

**Comment by weizhixiaoyi** [comment]
并不需要修改。fuseki_conf.ttl文件中，只要修改tdb:location和ja:rulesFrom位置路径就行。
