### ISSUE TITLE
项目运行问题

### ISSUE THREAD

**Issue by ITBOX-ITBOY** [weizhixiaoyi/DouBan-KGQA#2]
我按照你的说明进行了相应的操作
![图片](https://user-images.githubusercontent.com/15922437/68454085-85861a00-0232-11ea-89a2-0e2521b20762.png)
![图片](https://user-images.githubusercontent.com/15922437/68454096-8fa81880-0232-11ea-9185-8ae828afa527.png)
这就是最终的结果了是吧，没有web 页面是吧

**Comment by weizhixiaoyi** [comment]
对的，没有web界面，但可以根据https://weizhixiaoyi.com/archives/380.html 方法，部署到微信公众号。

**Comment by ITBOX-ITBOY** [comment]
你跑这个json2sql.py文件中的单个方法时，没有报错吗
![图片](https://user-images.githubusercontent.com/15922437/68463755-54b1df00-024a-11ea-9d95-d67aafbc94ab.png)

**Comment by weizhixiaoyi** [comment]
没有报错。
